{
 "title": "Sample Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "REST Api Activity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{uri!=\"/actuator/prometheus\", exception=\"None\"}[5m])"
    },
    {
     "expr": "rate(http_server_requests_seconds_count{uri!=\"/actuator/prometheus\",status!=\"200\"}[5m])"
    }
   ]
  },
  {
   "title": "sum(count_over_time({job=\"spring-app\"}[30m])) by (level)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"spring-app\"}[30m])) by (level)"
    }
   ]
  },
  {
   "title": "REST api Avg Response Time (ms)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum{uri!=\"/actuator/prometheus\", status!=\"500\"}[5m])/rate(http_server_requests_seconds_count{uri!=\"/actuator/prometheus\",status!=\"500\"}[5m])*1000"
    }
   ]
  },
  {
   "title": "{job=\"spring-app\",level=\"ERROR\"}",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "{job=\"spring-app\",level=\"ERROR\"}"
    }
   ]
  }
 ]
}