server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: spring-app
      __path__: /var/log/spring.log
  pipeline_stages:
      - json:
          expressions:
            level: level
            threadId: threadId
            message: message
            loggerName: loggerName
      - labels:
          level:
          threadId:
          message:
          loggerName: